# Generated by Django 5.0.6 on 2024-06-04 01:19

import family.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_alter_familymember_bio_alter_familymember_deathdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relations',
            name='child',
            field=models.IntegerField(verbose_name=family.models.FamilyMember),
        ),
        migrations.RemoveField(
            model_name='relations',
            name='parent',
        ),
        migrations.AddField(
            model_name='relations',
            name='parent',
            field=models.ManyToManyField(related_name='children', to='family.familymember'),
        ),
    ]
