# Generated by Django 5.0.6 on 2024-06-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0005_alter_familymember_bio_alter_familymember_borndate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relations',
            name='child',
        ),
        migrations.AddField(
            model_name='relations',
            name='childs',
            field=models.ManyToManyField(related_name='children', to='family.familymember'),
        ),
        migrations.AlterField(
            model_name='relations',
            name='parent',
            field=models.ManyToManyField(related_name='parent', to='family.familymember'),
        ),
    ]
