# Generated by Django 5.0.6 on 2024-06-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_remove_relations_child_relations_childs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relations',
            old_name='childs',
            new_name='child',
        ),
    ]
