# Generated by Django 5.0.6 on 2024-06-04 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0007_rename_childs_relations_child'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='familymember',
            options={'verbose_name': 'человека', 'verbose_name_plural': 'Члены семьи'},
        ),
        migrations.RemoveField(
            model_name='relations',
            name='child',
        ),
        migrations.RemoveField(
            model_name='relations',
            name='parent',
        ),
        migrations.AddField(
            model_name='relations',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='family.familymember'),
        ),
        migrations.AddField(
            model_name='relations',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='family.familymember'),
        ),
    ]
