# Generated by Django 5.0.6 on 2024-06-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0008_alter_familymember_options_remove_relations_child_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='photos/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фоторулетка',
            },
        ),
        migrations.AlterModelOptions(
            name='relations',
            options={'verbose_name': 'Взаимотношение', 'verbose_name_plural': 'Взаимотношения'},
        ),
    ]
